# Generated by Django 6.0.2 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_booking_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="booking",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="booking",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="booking",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]

