# Generated by Django 6.0.2 on 2026-03-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_newsletter_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("message", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="NewsletterSubscriber",
        ),
    ]

