from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("admin-login/", views.admin_login_page, name="admin_login_page"),
    path("admin-forgot-password/", views.admin_forgot_password_page, name="admin_forgot_password_page"),
    path("admin-signup/", views.admin_signup_page, name="admin_signup_page"),
    path("shopkeeper-logout/", views.shopkeeper_logout, name="shopkeeper_logout"),
    path("Home_index.html", views.home, name="home_file"),
    path("Car.html", views.cars_page, name="cars_page"),
    path("Bikes.html", views.bikes_page, name="bikes_page"),
    path("AllPartners.html", views.partners_page, name="partners_page"),
    path("Search.html", views.search_page, name="search_page"),
    path("search/", views.search_page, name="search_page_alias"),
    path("MyBooking.html", views.my_bookings_page, name="my_bookings_page"),
    path("profile.html", views.profile_page, name="profile_page"),
    path("login.html", views.login_page, name="login_page"),
    path("forgot-password.html", views.user_forgot_password_page, name="user_forgot_password_page"),
    path("signup.html", views.signup_page, name="signup_page"),
    path("Book_now.html", views.book_now_page, name="book_now_page"),
    path("payment.html", views.payment_page, name="payment_page"),
    path("admin/admin_login.html", views.admin_login_page, name="legacy_admin_login_page"),
    path("admin/admin_signup.html", views.admin_signup_page, name="legacy_admin_signup_page"),
    path("dashboard/", views.owner_dashboard, name="owner_dashboard"),
    path("admin-dashboard/", views.owner_dashboard, name="admin_dashboard_alias"),
    path("management/profile/", views.owner_profile_manage, name="owner_profile_manage"),
    path("api/profile/update-email/", views.profile_update_email, name="profile_update_email"),
    path("management/vehicles/", views.vehicle_manage, name="vehicle_manage"),
    path("management/vehicles/<int:vehicle_id>/edit/", views.vehicle_edit, name="vehicle_edit"),
    path("management/vehicles/<int:vehicle_id>/delete/", views.vehicle_delete, name="vehicle_delete"),
    path("management/vehicle-images/<int:image_id>/delete/", views.vehicle_image_delete, name="vehicle_image_delete"),
    path("management/bookings/", views.booking_manage, name="booking_manage"),
    path("management/expenses/", views.expense_manage, name="expense_manage"),
    path(
        "management/bookings/<int:booking_id>/decision/",
        views.booking_decision,
        name="booking_decision",
    ),
    path("api/dashboard/", views.owner_dashboard_api, name="owner_dashboard_api"),
    path("api/vehicles/", views.vehicle_list, name="vehicle_list"),
    path("api/bookings/", views.booking_list, name="booking_list"),
    path("api/bookings/create/", views.create_booking, name="create_booking"),
    path("api/bookings/cancel/", views.cancel_booking, name="cancel_booking"),
    path("api/expenses/add/", views.add_expense, name="add_expense"),
    path("api/otp/send/", views.otp_send, name="otp_send"),
    path("api/otp/verify/", views.otp_verify, name="otp_verify"),
    path("api/payments/razorpay/order/", views.razorpay_create_order, name="razorpay_create_order"),
    path("api/payments/razorpay/verify/", views.razorpay_verify_payment, name="razorpay_verify_payment"),
    path("api/feedback/submit/", views.feedback_submit, name="feedback_submit"),
    path("api/customers/profile/upsert/", views.customer_profile_upsert, name="customer_profile_upsert"),
    path("api/customers/profile/update-email/", views.customer_profile_update_email, name="customer_profile_update_email"),
]
