apiVersion: v1
kind: Service
metadata:
  name: royalwheels-web
  namespace: royalwheels
  labels:
    app: royalwheels-web
spec:
  selector:
    app: royalwheels-web
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
