# Generated by Django 6.0.2 on 2026-03-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_end_time_booking_rental_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cod', 'Cash on Delivery')], default='pending', max_length=10),
        ),
    ]
