# Generated by Django 6.0.2 on 2026-03-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_feedback_and_remove_newsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("lpu_id", models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ("license_number", models.CharField(blank=True, max_length=60)),
                ("driving_license_doc", models.FileField(blank=True, null=True, upload_to="customer_docs/licenses/")),
                ("student_id_doc", models.FileField(blank=True, null=True, upload_to="customer_docs/student_ids/")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]

