# Generated by Django 5.2.12 on 2026-03-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cloudinary_document_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
